name: "Set up config files for Design Dashboard"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares a config.js file for a data export."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  config_base:
    description: Path to the base folder with the config file(s)
    required: false
    default: 'src/config'
  api_origin:
    description: "API Server name for hitting the ogd-server api"
    required: true
    default: 'api placeholder'
  api_path:
    description: "Path on the server for hitting the ogd-server api"
    required: true
    default: 'path placeholder'
  package_home:
    description: "URL of the package homepage location"
    required: true
    default: 'homepage placeholder'
runs:
  using: "composite"
  steps:
    - name: Set up config
      run: cp ${{inputs.config_base}}/config.js.template ${{inputs.config_base}}/config.js 
      shell: bash
    - name: Set API origin server
      run: sed -i 's@API_ORIGIN_DEFAULT@${{inputs.api_origin}}@g' ${{inputs.config_base}}/config.js
      shell: bash
    - name: Set API path on server
      run: sed -i 's@API_PATH_DEFAULT@${{inputs.api_path}}@g' ${{inputs.config_base}}/config.js
      shell: bash
    - name: Set dashboard base directory
      run: sed -i 's@BASE_URL@${{inputs.package_home}}@g' ${{inputs.config_base}}/config.js
      shell: bash
    - name: Set package homepage
      run: sed -i 's@BASE_PATH@${{inputs.package_home}}@g' next.config.js
      shell: bash