name: "Set up config file for a run"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares a config.js file for a data export."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  api_origin:
    description: "API Server name for hitting the ogd-server api"
    required: true
    default: 'api placeholder'
  api_path:
    description: "Path on the server for hitting the ogd-server api"
    required: true
    default: 'path placeholder'
  package_home:
    description: "URL of the package homepage location"
    required: true
    default: 'homepage placeholder'
runs:
  using: "composite"
  steps:
    - name: Set up config
      run: cp src/config.js.template src/config.js 
      shell: bash
    - name: Set API origin server
      run: sed -i 's@API_ORIGIN_DEFAULT@${{inputs.api_origin}}@g' src/config.js
      shell: bash
    - name: Set API path on server
      run: sed -i 's@API_PATH_DEFAULT@${{inputs.api_path}}@g' src/config.js
      shell: bash
    - name: Set dashboard base directory
      run: sed -i 's@BASE_URL@${{inputs.package_home}}@g' src/config.js
      shell: bash
    - name: Set package homepage
      run: sed -i 's@PACKAGE_HOMEPAGE@${{inputs.package_home}}@g' package.json
      shell: bash