name: "Set up config files for Design Dashboard"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares a config.js file for a data export."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  env_base:
    description: Path to the base folder with the config file(s)
    required: false
    default: '.'
  api_origin:
    description: "API Server name for hitting the ogd-server api"
    required: true
    default: 'api placeholder'
  api_path:
    description: "Path on the server for hitting the ogd-server api"
    required: true
    default: 'path placeholder'
  package_home:
    description: "URL of the package homepage location"
    required: true
    default: 'homepage placeholder'
  gtag:
    description: "The Google Analytics ID/Tag"
    required: true
    default: 'gtag placeholder'
runs:
  using: "composite"
  steps:
    - name: Set up environment file
      run: cp ${{inputs.config_base}}/.env.example ${{inputs.config_base}}/.env.local
      shell: bash
    - name: Set API base path
      run: sed -i 's@BASE_URL=@BASE_URL=${{inputs.api_origin}}/${{inputs.api_path}}@g' ${{inputs.config_base}}/.env.local
      shell: bash
    - name: Set Google Analytics
      run: sed -i 's@BASE_URL=@BASE_URL=${{inputs.gtag}}@g' ${{inputs.config_base}}/.env.local
      shell: bash
    - name: Set package homepage
      run: sed -i 's@BASE_PATH@${{inputs.package_home}}@g' next.config.js
      shell: bash
      